### ISSUE TITLE
Error While scanning

### ISSUE THREAD

**Issue by kali64amd** [WeebSec/admin-san#1]
hi, there

I'm getting error while scanning so please advise. Appreciate your help.

Traceback (most recent call last):
  File "admin-san.py", line 80, in <module>
    loop.run_until_complete(future)
  File "/usr/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "admin-san.py", line 74, in run
    await responses
  File "admin-san.py", line 46, in fetch
    async with session.get(url) as response: 
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client.py", line 855, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client.py", line 391, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/client_reqrep.py", line 757, in start
    message, payload = await self._protocol.read()
  File "/usr/local/lib/python3.6/dist-packages/aiohttp/streams.py", line 543, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: None

**Comment by FuzzyRabbit** [comment]
Hello, 
Would you please let me know what site you were scanning and if this error only shows on all sites or just one. Any more info will greatly help me figure out how to deal with this error.
